import {
    ar_bookingAndReservations,
    ar_pickdropoff,
    ar_pricePayments,
    ar_vehicles,
    ar_waitingTimeCharges,
    bookingAndReservations,
    es_bookingAndReservations,
    es_pickdropoff,
    es_pricePayments,
    es_vehicles,
    es_waitingTimeCharges,
    it_bookingAndReservations,
    it_pickdropoff,
    it_pricePayments,
    it_vehicles,
    it_waitingTimeCharges,
    pickdropoff, pricePayments,
    ru_bookingAndReservations,
    ru_pickdropoff,
    ru_pricePayments,
    ru_vehicles,
    ru_waitingTimeCharges,
    tr_bookingAndReservations,
    tr_pickdropoff, tr_pricePayments,
    tr_vehicles, tr_waitingTimeCharges,
    vehicles, waitingTimeCharges, zh_bookingAndReservations, zh_pickdropoff, zh_pricePayments, zh_vehicles, zh_waitingTimeCharges
} from '../../constants/faqs'
// /pickdropoff true
//tr_waitingTimeCharges true
// Create a mapping for language-specific content
export const contentMap = {
    en: {
        bookingAndReservations,
        pricePayments,
        waitingTimeCharges,
        vehicles,
        pickdropoff,
        titles: {
            bookingAndReservations: "Booking and Reservations",
            pricePayments: "Pricing and Payment",
            waitingTimeCharges: "Waiting Time Charges",
            vehicles: "Vehicles and Services",
            pickdropoff: "Pickup and Drop-off",
        },
    },
    tr: {
        bookingAndReservations: tr_bookingAndReservations,
        pricePayments: tr_pricePayments,
        waitingTimeCharges: tr_waitingTimeCharges,
        vehicles: tr_vehicles,
        pickdropoff: tr_pickdropoff,
        titles: {
            bookingAndReservations: "Rezervasyon ve Kayıtlar",
            pricePayments: "Fiyatlandırma ve Ödeme",
            waitingTimeCharges: "Bekleme Süresi Ücretleri",
            vehicles: "Araçlar ve Hizmetler",
            pickdropoff: "Alım ve Bırakma Noktaları",
        },
    },
    ar: {
        bookingAndReservations: ar_bookingAndReservations,
        pricePayments: ar_pricePayments,
        waitingTimeCharges: ar_waitingTimeCharges,
        vehicles: ar_vehicles,
        pickdropoff: ar_pickdropoff,
        titles: {
            bookingAndReservations: "حجوزات والحجز",
            pricePayments: "التسعير والدفع",
            waitingTimeCharges: "رسوم وقت الانتظار",
            vehicles: "المركبات والخدمات",
            pickdropoff: "الاستقبال والتوصيل",
        },
    },
    ru: {
        bookingAndReservations: ru_bookingAndReservations,
        pricePayments: ru_pricePayments,
        waitingTimeCharges: ru_waitingTimeCharges,
        vehicles: ru_vehicles,
        pickdropoff: ru_pickdropoff,
        titles: {
            bookingAndReservations: "Бронирование и резервирование",
            pricePayments: "Ценообразование и оплата",
            waitingTimeCharges: "Тарифы за ожидание",
            vehicles: "Транспортные средства и услуги",
            pickdropoff: "Подбор и Высадка",
        },
    },
    zh: {
        bookingAndReservations: zh_bookingAndReservations,
        pricePayments: zh_pricePayments,
        waitingTimeCharges: zh_waitingTimeCharges,
        vehicles: zh_vehicles,
        pickdropoff: zh_pickdropoff,
        titles: {
            bookingAndReservations: "预订和预约",
            pricePayments: "定价和支付",
            waitingTimeCharges: "等待时间费用",
            vehicles: "车辆和服务",
            pickdropoff: "接送",
        },
    },
    es: {
        bookingAndReservations: es_bookingAndReservations,
        pricePayments: es_pricePayments,
        waitingTimeCharges: es_waitingTimeCharges,
        vehicles: es_vehicles,
        pickdropoff: es_pickdropoff,
        titles: {
            bookingAndReservations: "Reservas y Reservaciones",
            pricePayments: "Precios y Pago",
            waitingTimeCharges: "Cargos por Tiempo de Espera",
            vehicles: "Vehículos y Servicios",
            pickdropoff: "Recogida y Entrega",
        },
    },
    it: {
        bookingAndReservations: it_bookingAndReservations,
        pricePayments: it_pricePayments,
        waitingTimeCharges: it_waitingTimeCharges,
        vehicles: it_vehicles,
        pickdropoff: it_pickdropoff,
        titles: {
            bookingAndReservations: "Prenotazioni e Riservazioni",
            pricePayments: "Prezzi e Pagamento",
            waitingTimeCharges: "Costi per Tempo di Attesa",
            vehicles: "Veicoli e Servizi",
            pickdropoff: "Ritiro e Consegna",
        },
    },
};
